version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo Install started on `date`
      - apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - |
        cat << EOF > backend.tf
        provider "aws" {
          region     = "${AWS_REGION}"
        }

        terraform {
          backend "s3" {
            bucket = "${STATE_BUCKET}"
            key    = "${REPOSITORY_NAME}/terraform.tfstate"
            region = "${AWS_REGION}"
          }
        }
        EOF
      - terraform init -no-color
      - terraform plan -no-color
  build:
    commands:
      - echo Build started on `date`
      - terraform apply -auto-approve -no-color
  post_build:
    commands:
      - echo Post-build started on `date`
      - terraform destroy -no-color -force
artifacts:
  files:
    - '**/*'